version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: short-dase-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: short-dash
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres-data:/bitnami/postgresql

volumes:
  .postgres-data:
