version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=short
      - POSTGRES_PASSWORD=dash
      - POSTGRES_DB=short_dash
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
