import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import type { ReactNode } from "react";
import { Providers } from "./providers";

import { cn } from "@/lib/utils";
import "../styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: {
    absolute: "Short Dash",
    template: "%s | " + "Short Dash",
  },
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" className={cn(inter.variable, mono.variable)} suppressHydrationWarning>
      <body className={"min-h-screen bg-background font-sans antialiased"} suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
