import { Metadata } from "next";

export const application = {
  name: "Short Dash",
  version: "v0.0.2",
  author: "Lucas Santos",
};

export const publicMetadata: Metadata = {
  authors: [{ name: application.author, url: "https://github.com/LucasSantus" }],
  category: "developer",
  creator: application.author,
  title: {
    absolute: application.name,
    template: "%s | ".concat(application.name),
  },
  description: "Generated by create next app",
  keywords: [
    application.author,
    "Short Dash",
    "Short",
    "Dash",
    "Frontend",
    "UX Design",
    "Software",
    "Brazil",
    "Vercel",
    "Next",
    "React",
    "TypeScript",
    "TailwindCSS",
  ],
  publisher: application.author,
};
