import { Metadata } from "next";
import { Author } from "next/dist/lib/metadata/types/metadata-types";

interface Application {
  name: string;
  version: string;
  authors: Author[];
  creator: string;
}

export const application: Application = {
  name: "Short Dash",
  version: "v0.0.2",
  authors: [
    {
      name: "Lucas Santos",
      url: "https://github.com/LucasSantus",
    },
  ],
  creator: "Lucas Santos",
};

export const publicMetadata: Metadata = {
  authors: application.authors,
  category: "developer",
  creator: application.creator,
  title: {
    absolute: application.name,
    template: "%s | ".concat(application.name),
  },
  description: "Generated by create next app",
  keywords: [
    // application.author,
    "Short Dash",
    "Short",
    "Dash",
    "Frontend",
    "UX Design",
    "Software",
    "Brazil",
    "Vercel",
    "Next",
    "React",
    "TypeScript",
    "TailwindCSS",
  ],
  publisher: application.creator,
};
